### ISSUE TITLE
Installation issue (fatal error: lemon/list_graph.h: No such file or directory)

### ISSUE THREAD

**Issue by hermes1130** [studla/RYUTO#1]
Hello there,

I've followed the exact instruction to install ryuto and the dependencies. However, the "make" commend to compile ryuto shows me always the error written in the title. My research to solve this issue was not successful, so I'm writing you to ask if you can guide me in this particular circumstance. 

This was the "configure" commend
$ ./configure --with-zlib=/home/hermes1130/Data/ryuto/libraries_to_install/zlib-1.2.11/include --with-boost=/home/hermes1130/anaconda3/envs/boost --with-htslib=/home/hermes1130/Data/ryuto/libraries_to_install/htslib-develop --with-clp=/home/hermes1130/Data/ryuto/libraries_to_install/Clp-1.16.11 --with-lemon=/home/hermes1130/Data/ryuto/libraries_to_install/lemon-f51c01a1b88e/build --prefix=/home/hermes1130/Data/ryuto/RYUTO-master/
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking how to run the C++ preprocessor... g++ -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking if zlib is wanted... yes
checking for inflate in -lz... yes
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
checking for inflateEnd in -lz... yes
checking zlib in /usr... ok
checking if HTS is wanted... yes
checking sam.h usability... yes
checking sam.h presence... yes
checking for sam.h... yes
checking for hts_open in -lhts... yes
checking htslib... ok
checking for g++ option to support OpenMP... -fopenmp
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for boostlib >= 1.3... yes
./configure: line 4593: LDFLAGS: command not found
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking whether the Boost::Program_Options library is available... yes
checking for exit in -lboost_program_options... yes
checking if lemon is wanted... yes
checking lemon... ok
checking if clp is wanted... yes
checking clp... ok
checking whether C++ compiler accepts -std=c++0x... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: executing depfiles commands

This is "make" commend
make
Making all in src
make[1]: Entering directory '/home/hermes1130/Data/ryuto/RYUTO-master/src'
depbase=`echo Logger/logger.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DPACKAGE_NAME=\"ttrans\" -DPACKAGE_TARNAME=\"ttrans\" -DPACKAGE_VERSION=\"1.0\" -DPACKAGE_STRING=\"ttrans\ 1.0\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"ttrans\" -DVERSION=\"1.0\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_LIBZ=1 -DHAVE_BOOST=/\*\*/ -DHAVE_BOOST_PROGRAM_OPTIONS=/\*\*/ -I.  -I/home/hermes1130/Data/ryuto/libraries_to_install/htslib-develop/include/htslib/ -I/home/hermes1130/anaconda3/envs/boost/include -I/home/hermes1130/Data/ryuto/libraries_to_install/lemon-f51c01a1b88e/build/include/ -fopenmp -I/home/hermes1130/Data/ryuto/libraries_to_install/Clp-1.16.11/include/ -L/usr/lib -Wl,-rpath,/usr/lib/  -O2 -std=c++0x -MT Logger/logger.o -MD -MP -MF $depbase.Tpo -c -o Logger/logger.o Logger/logger.cc &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo Controller/bam_controller.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DPACKAGE_NAME=\"ttrans\" -DPACKAGE_TARNAME=\"ttrans\" -DPACKAGE_VERSION=\"1.0\" -DPACKAGE_STRING=\"ttrans\ 1.0\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"ttrans\" -DVERSION=\"1.0\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_LIBZ=1 -DHAVE_BOOST=/\*\*/ -DHAVE_BOOST_PROGRAM_OPTIONS=/\*\*/ -I.  -I/home/hermes1130/Data/ryuto/libraries_to_install/htslib-develop/include/htslib/ -I/home/hermes1130/anaconda3/envs/boost/include -I/home/hermes1130/Data/ryuto/libraries_to_install/lemon-f51c01a1b88e/build/include/ -fopenmp -I/home/hermes1130/Data/ryuto/libraries_to_install/Clp-1.16.11/include/ -L/usr/lib -Wl,-rpath,/usr/lib/  -O2 -std=c++0x -MT Controller/bam_controller.o -MD -MP -MF $depbase.Tpo -c -o Controller/bam_controller.o Controller/bam_controller.cc &&\
mv -f $depbase.Tpo $depbase.Po
In file included from Controller/../Reader/../Graph/pre_graph/../overlap_graph/overlap_node.h:12:0,
                 from Controller/../Reader/../Graph/pre_graph/pre_graph.h:12,
                 from Controller/../Reader/reader_base.h:16,
                 from Controller/base_controller.h:13,
                 from Controller/bam_controller.h:11,
                 from Controller/bam_controller.cc:8:
Controller/../Reader/../Graph/pre_graph/../overlap_graph/range_helper.h:11:30: fatal error: lemon/list_graph.h: No such file or directory
 #include <lemon/list_graph.h>
                              ^
compilation terminated.
Makefile:747: recipe for target 'Controller/bam_controller.o' failed
make[1]: *** [Controller/bam_controller.o] Error 1
make[1]: Leaving directory '/home/hermes1130/Data/ryuto/RYUTO-master/src'
Makefile:366: recipe for target 'all

**Comment by TGatter** [comment]
Hi,
from what I see you did not point the linker to the correct installation location of Lemon, but instead to the build subfolder.
Make sure to run

```
cmake -DCMAKE_INSTALL_PREFIX=/home/username/lemon'
```
with your installation directory of choice when compiling lemon. Also run

```
make install
```
for Lemon in the build folder. Then point -with-lemon to the correct folder it was installed to.

Don't hesitate to message me should you need more assistance.

**Comment by hermes1130** [comment]
Thank you very much for your fast reply!

The problem is now solved thanks to your help :)
